### ISSUE TITLE
Could it be possible to open source your shiny DB code

### ISSUE THREAD

**Issue by yuanlizhanshi** [Chengwenwen1/scMMO-atlas#1]

**Comment by Chengwenwen1** [comment]
I appreciate your interest in my research and the Shiny app. However, for several reasons, I cannot share this part of the code publicly.

I recommend that you check out my published articles for details on the methodology. Please feel free to let me know if you have additional questions or need further discussion.

Thanks again for your understanding!

Best wishes.
Wenwen
