### ISSUE TITLE
Are these data overlapped with ENCODE project?

### ISSUE THREAD

**Issue by zjgbz** [Chengwenwen1/scMMO-atlas#2]
Hi Authors of scMMO-atlas,

Thank you for your awesome work, and this is indeed a very useful database. But I am wondering if your database has any overlap with ENCODE project? Thank you very much!

Best regards,
zjgbz

**Comment by Chengwenwen1** [comment]
Hi,

Thank you for your kind words about our database!

Regarding your question about overlap with the ENCODE project, while scMMO-atlas focuses on single-cell multimodal omics data, there may be some overlap in cell and tissue types with the ENCODE project. However, our database is specifically designed to provide comprehensive insights into multimodal omics, which may differ in scope and data types from ENCODE.

If you have any more questions or need further information, feel free to ask!

Best regards,
Wenwen

**Comment by zjgbz** [comment]
Hi Wenwen,

Thank you very much for your quick response. Actually, I am wondering if there is any datasets from your database overlapped with ENCODE. Your database consists of 10X datasets, GEO, and other datasets, and I am not sure if scMMO-atlas shared any datasets with ENCODE. But based on your response, I think that you mean that your scMMO-atlas does not share any explicit dataset with ENCODE, right? Thank you very much.

Best regards,
zjgbz
